
name: jaffle_shop
version: '1.0.0'
config-version: 2 # you must be using dbt v0.17.0 for this to work

profile: 'jaffle_shop'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


models:
  jaffle_shop:
    +materialized: table
    staging:
      +materialized: view
